### ISSUE TITLE
New endpoint and changed response from KMNI

### ISSUE THREAD

**Issue by vankappen** [ricbra/knmi-client#6]
Hi Ricbra,

The KNMI has updated their API, the new url is https://www.daggegevens.knmi.nl/klimatologie/daggegevens
and the regular expression in the response parser for matching the stations has a slight change:

'/# ([0-9]{3})\s+([0-9]+.[0-9]+)\s+([0-9]+.[0-9]+)\s+(-?[0-9]+.[0-9]+)\s+([A-Z\s\(\)]+)/'

Just remove the first :

After these changes it seems to be working again.

**Comment by ricbra** [comment]
Hi @vankappen 

It sounds you are more into the API then me right now (I'm not using this library anymore), would you like to work on a merge request to address these fixes?

**Comment by ricbra** [comment]
Closing this now, fix has been merged
